version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=pract
      - POSTGRES_PASSWORD=me456
      - POSTGRES_DB=test2
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgresql://pract:me456@db:5432/test2
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: test2
      POSTGRES_USER: pract
      POSTGRES_PASSWORD: me456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
